Carrito/urls.py
from django.urls import path
from . import views

app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

TiendaOnline/urls.py
from django.contrib import admin
from django.urls import path
from TiendaOnline import views
from Productos.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
urlpatterns = [
    path('', ProductListView.as_view(), name="index"),
    path('usuarios/login', views.login_view, name="login"),
    path('usuarios/logout', views.logout_view, name="logout"),
    path('usuarios/registro', views.register, name="register"),
    path('admin/', admin.site.urls),
    path('productos/', include('Productos.urls')),
    path('carrito/', include('Carrito.urls')),
    path('orden/', include('Ordenes.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/carts/snippets/add.html
{% load static %}

<form action="{% url 'carts:add' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <div class="">
    <!--d-inline es para que los componentes se encuentren en linea-->
    <input type="number" min="1" contenteditable="false" max="{{ product.stock }}"name="quantity" id="quantity" value="1" class="form-control-lg d-inline">
    <button type="submit" class="cart-btn d-inline">
    <i class="fas fa-shopping-cart"></i> Añadir al Carrito
    </button>
    </div>

</form>

templates/carts/snippets/remove.html
<form action="{% url 'carts:remove' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <button type="submit" class="btn btn-link text-danger" style="padding:0px">Eliminar</button>
    <input type="hidden" name="quantity" value="{{ cp.quantity}}">
</form>